// Code generated by ffcompile. DO NOT EDIT.
package featureflags

import (
	"context"
	"errors"
	"fmt"
)

type EvaluationContext struct {
	TargetingKey string
	Attributes   map[string]any
}

type Client interface {
	BooleanValue(ctx context.Context, key string, defaultValue bool, evalCtx EvaluationContext) (bool, error)
	StringValue(ctx context.Context, key string, defaultValue string, evalCtx EvaluationContext) (string, error)
	IntValue(ctx context.Context, key string, defaultValue int64, evalCtx EvaluationContext) (int64, error)
	FloatValue(ctx context.Context, key string, defaultValue float64, evalCtx EvaluationContext) (float64, error)
	ObjectValue(ctx context.Context, key string, defaultValue any, evalCtx EvaluationContext) (any, error)
}

type Evaluator struct {
	client Client
}

func New(client Client) Evaluator {
	return Evaluator{client: client}
}

var ErrInvalidObjectValue = errors.New("invalid object value")
var ErrInvalidListValue = errors.New("invalid list value")

func newEvaluationContext(attrs map[string]any) EvaluationContext {
	if attrs == nil {
		attrs = make(map[string]any)
	}
	return EvaluationContext{
		Attributes: attrs,
	}
}

func newEvaluationContextWithTargetingKey(attrs map[string]any, targetingKey string) EvaluationContext {
	evalCtx := newEvaluationContext(attrs)
	evalCtx.TargetingKey = targetingKey
	return evalCtx
}
func asObjectValue(value any) (map[string]any, error) {
	switch v := value.(type) {
	case nil:
		return nil, nil
	case map[string]any:
		return cloneMapValue(v), nil
	default:
		return nil, fmt.Errorf("%w: got %T", ErrInvalidObjectValue, value)
	}
}

func asListValue(value any) ([]any, error) {
	switch v := value.(type) {
	case nil:
		return nil, nil
	case []any:
		return cloneSliceValue(v), nil
	default:
		return nil, fmt.Errorf("%w: got %T", ErrInvalidListValue, value)
	}
}

func cloneAnyValue(value any) any {
	switch v := value.(type) {
	case map[string]any:
		return cloneMapValue(v)
	case []any:
		return cloneSliceValue(v)
	default:
		return v
	}
}

func cloneMapValue(value map[string]any) map[string]any {
	if value == nil {
		return nil
	}
	out := make(map[string]any, len(value))
	for key, item := range value {
		out[key] = cloneAnyValue(item)
	}
	return out
}

func cloneSliceValue(value []any) []any {
	if value == nil {
		return nil
	}
	out := make([]any, 0, len(value))
	for _, item := range value {
		out = append(out, cloneAnyValue(item))
	}
	return out
}

const (
	FlagQuotaLimit     = "quota-limit"
	FlagScoreThreshold = "score-threshold"
	FlagStarterBadges  = "starter-badges"
	FlagThemeConfig    = "theme-config"
)

func (e Evaluator) QuotaLimit(ctx context.Context) (int64, error) {
	var attrs map[string]any
	return e.client.IntValue(ctx, FlagQuotaLimit, 1, newEvaluationContext(attrs))
}

func (e Evaluator) ScoreThreshold(ctx context.Context) (float64, error) {
	var attrs map[string]any
	return e.client.FloatValue(ctx, FlagScoreThreshold, 0.5, newEvaluationContext(attrs))
}

func (e Evaluator) StarterBadges(ctx context.Context) ([]any, error) {
	var attrs map[string]any
	value, err := e.client.ObjectValue(ctx, FlagStarterBadges, []any{}, newEvaluationContext(attrs))
	if err != nil {
		return nil, err
	}
	return asListValue(value)
}

func (e Evaluator) ThemeConfig(ctx context.Context) (map[string]any, error) {
	var attrs map[string]any
	value, err := e.client.ObjectValue(ctx, FlagThemeConfig, map[string]any{"nested": map[string]any{"enabled": true}, "primary": "blue"}, newEvaluationContext(attrs))
	if err != nil {
		return nil, err
	}
	return asObjectValue(value)
}
