// Code generated by ffcompile. DO NOT EDIT.
package featureflags

import (
	"context"
)

type EvaluationContext struct {
	TargetingKey string
	Attributes   map[string]any
}

type Client interface {
	BooleanValue(ctx context.Context, key string, defaultValue bool, evalCtx EvaluationContext) (bool, error)
	StringValue(ctx context.Context, key string, defaultValue string, evalCtx EvaluationContext) (string, error)
	IntValue(ctx context.Context, key string, defaultValue int64, evalCtx EvaluationContext) (int64, error)
	FloatValue(ctx context.Context, key string, defaultValue float64, evalCtx EvaluationContext) (float64, error)
	ObjectValue(ctx context.Context, key string, defaultValue any, evalCtx EvaluationContext) (any, error)
}

type Evaluator struct {
	client Client
}

func New(client Client) Evaluator {
	return Evaluator{client: client}
}

func newEvaluationContext(attrs map[string]any) EvaluationContext {
	if attrs == nil {
		attrs = make(map[string]any)
	}
	return EvaluationContext{
		Attributes: attrs,
	}
}

func newEvaluationContextWithTargetingKey(attrs map[string]any, targetingKey string) EvaluationContext {
	evalCtx := newEvaluationContext(attrs)
	evalCtx.TargetingKey = targetingKey
	return evalCtx
}

const (
	FlagScoreThreshold = "score-threshold"
)

func (e Evaluator) ScoreThreshold(ctx context.Context) (float64, error) {
	var attrs map[string]any
	return e.client.FloatValue(ctx, FlagScoreThreshold, 0.5, newEvaluationContext(attrs))
}
