// Code generated by ffcompile. DO NOT EDIT.
package featureflags

import (
	"context"
)

type EvaluationContext struct {
	TargetingKey string
	Attributes   map[string]any
}

type Client interface {
	BooleanValue(ctx context.Context, key string, defaultValue bool, evalCtx EvaluationContext) (bool, error)
	StringValue(ctx context.Context, key string, defaultValue string, evalCtx EvaluationContext) (string, error)
	IntValue(ctx context.Context, key string, defaultValue int64, evalCtx EvaluationContext) (int64, error)
	FloatValue(ctx context.Context, key string, defaultValue float64, evalCtx EvaluationContext) (float64, error)
	ObjectValue(ctx context.Context, key string, defaultValue any, evalCtx EvaluationContext) (any, error)
}

type Evaluator struct {
	client Client
}

func New(client Client) Evaluator {
	return Evaluator{client: client}
}

func newEvaluationContext(attrs map[string]any) EvaluationContext {
	if attrs == nil {
		attrs = make(map[string]any)
	}
	return EvaluationContext{
		Attributes: attrs,
	}
}

func newEvaluationContextWithTargetingKey(attrs map[string]any, targetingKey string) EvaluationContext {
	evalCtx := newEvaluationContext(attrs)
	evalCtx.TargetingKey = targetingKey
	return evalCtx
}

const (
	FlagBannerMode = "banner-mode"
	FlagStaticHome = "static-home"
)

type BannerModeVariant string

const (
	BannerModeVariantAnnouncement BannerModeVariant = "announcement"
	BannerModeVariantControl      BannerModeVariant = "control"
)

func (e Evaluator) BannerMode(ctx context.Context) (BannerModeVariant, error) {
	var attrs map[string]any
	v, err := e.client.StringValue(ctx, FlagBannerMode, "control", newEvaluationContext(attrs))
	if err != nil {
		return "", err
	}
	return BannerModeVariant(v), nil
}

func (e Evaluator) StaticHome(ctx context.Context) (bool, error) {
	var attrs map[string]any
	return e.client.BooleanValue(ctx, FlagStaticHome, false, newEvaluationContext(attrs))
}
