// Code generated by ffcompile. DO NOT EDIT.
package featureflags

import (
	"context"
	"errors"
	"fmt"
	"strings"
)

type EvaluationContext struct {
	TargetingKey string
	Attributes   map[string]any
}

type Client interface {
	BooleanValue(ctx context.Context, key string, defaultValue bool, evalCtx EvaluationContext) (bool, error)
	StringValue(ctx context.Context, key string, defaultValue string, evalCtx EvaluationContext) (string, error)
	IntValue(ctx context.Context, key string, defaultValue int64, evalCtx EvaluationContext) (int64, error)
	FloatValue(ctx context.Context, key string, defaultValue float64, evalCtx EvaluationContext) (float64, error)
	ObjectValue(ctx context.Context, key string, defaultValue any, evalCtx EvaluationContext) (any, error)
}

type Evaluator struct {
	client Client
}

func New(client Client) Evaluator {
	return Evaluator{client: client}
}

var ErrMissingTargetingKey = errors.New("missing targetingKey")

func withTargetingKeyAttributes(attrs map[string]any, targetingKey string, paths ...string) map[string]any {
	if targetingKey == "" || len(paths) == 0 {
		return attrs
	}
	if attrs == nil {
		attrs = make(map[string]any)
	}
	for _, path := range paths {
		setPath(attrs, path, targetingKey)
	}
	return attrs
}

func newEvaluationContext(attrs map[string]any) EvaluationContext {
	if attrs == nil {
		attrs = make(map[string]any)
	}
	return EvaluationContext{
		Attributes: attrs,
	}
}

func newEvaluationContextWithTargetingKey(attrs map[string]any, targetingKey string) EvaluationContext {
	evalCtx := newEvaluationContext(attrs)
	evalCtx.TargetingKey = targetingKey
	return evalCtx
}
func setPath(root map[string]any, path string, value any) {
	if path == "" {
		return
	}
	parts := strings.Split(path, ".")
	current := root
	for _, part := range parts[:len(parts)-1] {
		next, ok := current[part].(map[string]any)
		if !ok {
			next = make(map[string]any)
			current[part] = next
		}
		current = next
	}
	current[parts[len(parts)-1]] = value
}

const (
	FlagCheckoutRollout = "checkout-rollout"
	FlagHomeRollout     = "home-rollout"
)

type CheckoutRolloutVariant string

const (
	CheckoutRolloutVariantControl   CheckoutRolloutVariant = "control"
	CheckoutRolloutVariantTreatment CheckoutRolloutVariant = "treatment"
)

func (e Evaluator) CheckoutRollout(ctx context.Context, targetingKey string) (CheckoutRolloutVariant, error) {
	if targetingKey == "" {
		return "", fmt.Errorf("flag %s: %w", FlagCheckoutRollout, ErrMissingTargetingKey)
	}
	var attrs map[string]any
	attrs = withTargetingKeyAttributes(attrs, targetingKey, "user.id")
	v, err := e.client.StringValue(ctx, FlagCheckoutRollout, "control", newEvaluationContextWithTargetingKey(attrs, targetingKey))
	if err != nil {
		return "", err
	}
	return CheckoutRolloutVariant(v), nil
}

func (e Evaluator) HomeRollout(ctx context.Context, targetingKey string) (bool, error) {
	if targetingKey == "" {
		return false, fmt.Errorf("flag %s: %w", FlagHomeRollout, ErrMissingTargetingKey)
	}
	var attrs map[string]any
	attrs = withTargetingKeyAttributes(attrs, targetingKey, "user.id")
	return e.client.BooleanValue(ctx, FlagHomeRollout, false, newEvaluationContextWithTargetingKey(attrs, targetingKey))
}
