// Code generated by ffcompile. DO NOT EDIT.
package testflags

import (
	"context"
	"strings"
)

type EvaluationContext struct {
	TargetingKey string
	Attributes   map[string]any
}

type Client interface {
	BooleanValue(ctx context.Context, key string, defaultValue bool, evalCtx EvaluationContext) (bool, error)
	StringValue(ctx context.Context, key string, defaultValue string, evalCtx EvaluationContext) (string, error)
	IntValue(ctx context.Context, key string, defaultValue int64, evalCtx EvaluationContext) (int64, error)
	FloatValue(ctx context.Context, key string, defaultValue float64, evalCtx EvaluationContext) (float64, error)
	ObjectValue(ctx context.Context, key string, defaultValue any, evalCtx EvaluationContext) (any, error)
}

type Evaluator struct {
	client Client
}

func New(client Client) Evaluator {
	return Evaluator{client: client}
}

func newEvaluationContext(attrs map[string]any) EvaluationContext {
	if attrs == nil {
		attrs = make(map[string]any)
	}
	return EvaluationContext{
		Attributes: attrs,
	}
}

func newEvaluationContextWithTargetingKey(attrs map[string]any, targetingKey string) EvaluationContext {
	evalCtx := newEvaluationContext(attrs)
	evalCtx.TargetingKey = targetingKey
	return evalCtx
}

type EvalContext struct {
	UserCountry string
	UserScores  []int
	UserTags    []string
}

func (e EvalContext) toAttributes() map[string]any {
	out := make(map[string]any)
	setPath(out, "user.country", e.UserCountry)
	setPath(out, "user.scores", e.UserScores)
	setPath(out, "user.tags", e.UserTags)
	return out
}

func setPath(root map[string]any, path string, value any) {
	if path == "" {
		return
	}
	parts := strings.Split(path, ".")
	current := root
	for _, part := range parts[:len(parts)-1] {
		next, ok := current[part].(map[string]any)
		if !ok {
			next = make(map[string]any)
			current[part] = next
		}
		current = next
	}
	current[parts[len(parts)-1]] = value
}

const (
	FlagInferredCollections = "inferred-collections"
)

func (e Evaluator) InferredCollections(ctx context.Context, ec EvalContext) (bool, error) {
	attrs := ec.toAttributes()
	return e.client.BooleanValue(ctx, FlagInferredCollections, false, newEvaluationContext(attrs))
}
